In [1]:
import pandas as pd
from acquire import get_zillow_data, get_zillow_data_full, acquire_zillow

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

In [3]:
df = get_zillow_data()
df.head()

   parcelid  logerror transactiondate airconditioningdesc architecturalstyledesc  buildingclassdesc heatingorsystemdesc        propertylandusedesc storydesc typeconstructiondesc  basementsqft  bathroomcnt  bedroomcnt  calculatedbathnbr  finishedfloor1squarefeet  calculatedfinishedsquarefeet  finishedsquarefeet12  finishedsquarefeet13  finishedsquarefeet15  finishedsquarefeet50  finishedsquarefeet6    fips  fireplacecnt  fullbathcnt  garagecarcnt  garagetotalsqft  hashottuborspa    latitude    longitude  lotsizesquarefeet  poolcnt  poolsizesum propertycountylandusecode propertyzoningdesc  rawcensustractandblock  roomcnt  threequarterbathnbr  unitcnt  yardbuildingsqft17  yardbuildingsqft26  yearbuilt  numberofstories  fireplaceflag  structuretaxvaluedollarcnt  taxvaluedollarcnt  assessmentyear  landtaxvaluedollarcnt  taxamount taxdelinquencyflag  taxdelinquencyyear  censustractandblock  regionidzip  buildingqualitytypeid  decktypeid  pooltypeid10  pooltypeid2  pooltypeid7  regionidcity  regionidcounty  regionidneighborhood
0  14297519  0.025595      2017-01-01                 NaN                    NaN                NaN                 NaN  Single Family Residential       NaN                  NaN           NaN          3.5         4.0                3.5                       NaN                        3100.0                3100.0                   NaN                   NaN                   NaN                  NaN  6059.0           NaN          3.0           2.0            633.0             NaN  33634931.0 -117869207.0             4506.0      NaN          NaN                       122                NaN            6.059063e+07      0.0                  1.0      NaN                 NaN                 NaN     1998.0              NaN            NaN                    485713.0          1023282.0          2016.0               537569.0   11013.72                NaN                 NaN         6.059063e+13      96978.0                    NaN         NaN           NaN          NaN          NaN       53571.0          1286.0                   NaN
1  17052889  0.055619      2017-01-01                 NaN                    NaN                NaN                 NaN  Single Family Residential       NaN                  NaN           NaN          1.0         2.0                1.0                    1465.0                        1465.0                1465.0                   NaN                   NaN                1465.0                  NaN  6111.0           1.0          1.0           1.0              0.0             NaN  34449266.0 -119281531.0            12647.0      NaN          NaN                      1110                NaN            6.111001e+07      5.0                  NaN      NaN                 NaN                 NaN     1967.0              1.0            NaN                     88000.0           464000.0          2016.0               376000.0    5672.48                NaN                 NaN         6.111001e+13      97099.0                    NaN         NaN           NaN          NaN          NaN       13091.0          2061.0                   NaN
2  14186244  0.005383      2017-01-01                 NaN                    NaN                NaN                 NaN  Single Family Residential       NaN                  NaN           NaN          2.0         3.0                2.0                       NaN                        1243.0                1243.0                   NaN                   NaN                   NaN                  NaN  6059.0           NaN          2.0           2.0            440.0             NaN  33886168.0 -117823170.0             8432.0      1.0          NaN                       122                NaN            6.059022e+07      6.0                  NaN      NaN                 NaN                 NaN     1962.0              1.0            NaN                     85289.0           564778.0          2016.0               479489.0    6488.30                NaN                 NaN         6.059022e+13      97078.0                    NaN         NaN           NaN          NaN          1.0       21412.0          1286.0                   NaN
3  12177905 -0.103410      2017-01-01                 NaN                    NaN                NaN             Central  Single Family Residential       NaN                  NaN           NaN          3.0         4.0                3.0                       NaN                        2376.0                2376.0                   NaN                   NaN                   NaN                  NaN  6037.0           NaN          3.0           NaN              NaN             NaN  34245180.0 -118240722.0            13038.0      1.0          NaN                      0101         LCR110000*            6.037300e+07      0.0                  NaN      1.0                 NaN                 NaN     1970.0              NaN            NaN                    108918.0           145143.0          2016.0                36225.0    1777.51                NaN                 NaN         6.037300e+13      96330.0                    8.0         NaN           NaN          NaN          1.0      396551.0          3101.0                   NaN
4  12095076 -0.001011      2017-01-01             Central                    NaN                NaN             Central  Single Family Residential       NaN                  NaN           NaN          3.0         4.0                3.0                       NaN                        2962.0                2962.0                   NaN                   NaN                   NaN                  NaN  6037.0           NaN          3.0           NaN              NaN             NaN  34145202.0 -118179824.0            63000.0      1.0          NaN                      0101               PSR2            6.037461e+07      0.0                  NaN      1.0                 NaN                 NaN     1950.0              NaN            NaN                    276684.0           773303.0          2016.0               496619.0    9516.26                NaN                 NaN         6.037461e+13      96293.0                    9.0         NaN           NaN          NaN          1.0       47019.0          3101.0              274684.0

In [ ]:
print("Shape of the DataFrame:", df.shape)
print('\n')
print("\nInfo:")
df.info()

In [ ]:
df.shape

In [ ]:
print("\nSummary Statistics:")
print()
print(df.describe())

In [ ]:
print("\nValue Counts for Categorical Columns:")
for column in df.select_dtypes(include='object'):
    print(f"Column: {column}")
    print(df[column].value_counts())
    print('\n')

In [ ]:
df['transactiondate'] = pd.to_datetime(df['transactiondate'])
print("\nMissing Values:")
print(df.isna().sum())

In [ ]:
numerical_df = df.select_dtypes(include=['number'])

print("\nCorrelation Matrix:")
# Calculate the correlation matrix
correlation_matrix = numerical_df.corr()
print(correlation_matrix)

In [ ]:
# Calculate the correlation matrix for the numerical columns
numerical_df = df.select_dtypes(include=['number'])
correlation_matrix = numerical_df.corr()

# Create a DataFrame to store the top 5 correlated columns for each column
top_correlated_columns = pd.DataFrame(index=correlation_matrix.columns, columns=range(1, 6))

# Iterate through the columns of the correlation matrix
for col in correlation_matrix.columns:
    # Sort the correlations for the current column in descending order
    sorted_corr = correlation_matrix[col].sort_values(ascending=False)
    
    # Select the top 5 correlated columns (excluding the column itself)
    top_correlated_columns.loc[col] = sorted_corr[1:6].index

# Print or use top_correlated_columns DataFrame
print(top_correlated_columns)

In [ ]:
top_correlated_columns_transposed = top_correlated_columns.T
top_correlated_columns_transposed

In [ ]:
def missing_value_summary(df):
    # Calculate the number of missing values for each column
    num_missing = df.isnull().sum()

    # Calculate the percentage of missing values for each column
    pct_missing = (num_missing / len(df)) * 100

    # Create a new DataFrame to store the summary
    summary_df = pd.DataFrame({'missing': num_missing, 'percent_missing': pct_missing})

    # Format the 'num_rows_missing' column as a whole percentage
    summary_df['percent_missing'] = summary_df['percent_missing'].apply(lambda x: f'{x:.0f}%')

    return summary_df

# Assuming you have a DataFrame called 'df' containing your data
summary = missing_value_summary(df).sort_values('percent_missing', ascending= False)

# Print the summary DataFrame
print(summary)

Remove rows that have no useful data

In [ ]:
df.drop(columns=['architecturalstyledesc','buildingclassdesc', 'storydesc', 'typeconstructiondesc', 'basementsqft', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet6', 'yardbuildingsqft26', 'fireplaceflag', 'pooltypeid10', 'poolsizesum', 'pooltypeid2', 'pooltypeid7', 'decktypeid', 'yardbuildingsqft17', 'finishedfloor1squarefeet', 'finishedsquarefeet50', 'numberofstories', 'garagecarcnt', 'garagetotalsqft', 'regionidneighborhood', 'buildingqualitytypeid', 'unitcnt'], inplace= True)

In [ ]:
def missing_value_summary(df):
    # Calculate the number of missing values for each column
    num_missing = df.isnull().sum()

    # Calculate the percentage of missing values for each column
    pct_missing = (num_missing / len(df)) * 100

    # Create a new DataFrame to store the summary
    summary_df = pd.DataFrame({'missing': num_missing, 'percent_missing': pct_missing})

    # Format the 'num_rows_missing' column as a whole percentage
    summary_df['percent_missing'] = summary_df['percent_missing'].apply(lambda x: f'{x:.0f}%')

    return summary_df

# Assuming you have a DataFrame called 'df' containing your data
summary = missing_value_summary(df).sort_values('missing', ascending= False)

# Print the summary DataFrame
print(summary)

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df['hashottuborspa'] = df['hashottuborspa'].fillna('N')
df['taxdelinquencyflag'] = df['taxdelinquencyflag'].fillna('N')
df['taxdelinquencyyear'] = df['taxdelinquencyyear'].fillna(0)
df['threequarterbathnbr'] = df['threequarterbathnbr'].fillna(0)
df['fireplacecnt'] = df['fireplacecnt'].fillna(0)
df['poolcnt'] = df['poolcnt'].fillna(0)
df['airconditioningdesc'] = df['airconditioningdesc'].fillna('None')
df['heatingorsystemdesc'] = df['heatingorsystemdesc'].fillna('None')
df['propertyzoningdesc'] = df['propertyzoningdesc'].fillna('None')

In [ ]:
# Drop rows where either bedroomcnt or bathroomcnt is 0
df = df[(df['bedroomcnt'] != 0) & (df['bathroomcnt'] != 0)]

In [ ]:
df.zip.unique()

In [ ]:
column_mapping = {
    'parcelid': 'parcel_id',
    'logerror': 'log_error',
    'transactiondate': 'transaction_date',
    'airconditioningdesc': 'ac_desc',
    'heatingorsystemdesc': 'heating_desc',
    'propertylandusedesc': 'property_type',
    'bathroomcnt': 'bathrooms',
    'bedroomcnt': 'bedrooms',
    'calculatedbathnbr': 'calc_bath_count',
    'calculatedfinishedsquarefeet': 'calc_finished_sf',
    'finishedsquarefeet12': 'finished_sf',
    'fips': 'fips',
    'fireplacecnt': 'fireplaces',
    'fullbathcnt': 'full_bathrooms',
    'hashottuborspa': 'hottub_spa',
    'latitude': 'latitude',
    'longitude': 'longitude',
    'lotsizesquarefeet': 'lot_size_sf',
    'poolcnt': 'pools',
    'propertycountylandusecode': 'county_land_use_code',
    'propertyzoningdesc': 'zoning',
    'rawcensustractandblock': 'rawcensus_tract_block',
    'roomcnt': 'rooms',
    'threequarterbathnbr': 'three_quarter_bathrooms',
    'yearbuilt': 'year_built',
    'structuretaxvaluedollarcnt': 'structure_tax_value',
    'taxvaluedollarcnt': 'tax_value',
    'assessmentyear': 'assessment_year',
    'landtaxvaluedollarcnt': 'land_tax_value',
    'taxamount': 'tax_amount',
    'taxdelinquencyflag': 'tax_delinquency',
    'taxdelinquencyyear': 'tax_delinquency_year',
    'censustractandblock': 'census_tract_block',
    'regionidzip': 'zip',
    'regionidcity': 'city',
    'regionidcounty': 'county'
}

# Rename the columns using the dictionary
df.rename(columns=column_mapping, inplace=True)

In [ ]:
# Filter rows where 'numberofstories' is NaN
filtered_df = df[pd.isna(df['numberofstories'])]

# Display the first few rows of the filtered DataFrame
filtered_df.head()

In [ ]:
def fips_map(df):
    """
    Map FIPS codes to county and state names and add them as new columns to a DataFrame.

    Parameters:
        df (pd.DataFrame): The DataFrame containing Zillow property data to be processed.

    Returns:
        pd.DataFrame: The DataFrame with two new columns 'county' and 'state' added based on the 'fips' column.
    """
    # Mapping of FIPS codes to county and state names
    fips_to_county_state = {
        6059: {'county': 'Orange', 'state': 'CA'},
        6111: {'county': 'Ventura', 'state': 'CA'},
        6037: {'county': 'Los Angeles', 'state': 'CA'},
    }

    # Add new columns 'county' and 'state' based on 'fips'
    df['county'] = df['fips'].map(lambda x: fips_to_county_state[x]['county'])
    df['state'] = df['fips'].map(lambda x: fips_to_county_state[x]['state'])

    return df

In [ ]:
all_rows = summary.index.tolist()
print(all_rows)

In [ ]:
desired_column_order = ['pooltypeid10', 'decktypeid', 'poolsizesum', 'pooltypeid2', 'hashottuborspa', 'taxdelinquencyyear', 'yardbuildingsqft17', 'taxdelinquencyflag', 'finishedfloor1squarefeet', 'finishedsquarefeet50', 'threequarterbathnbr', 'fireplacecnt', 'pooltypeid7', 'poolcnt', 'airconditioningdesc', 'numberofstories', 'garagecarcnt', 'garagetotalsqft', 'regionidneighborhood', 'buildingqualitytypeid', 'unitcnt', 'propertyzoningdesc', 'heatingorsystemdesc', 'regionidcity', 'lotsizesquarefeet', 'longitude', 'regionidcounty', 'transactiondate', 'propertylandusedesc', 'bathroomcnt', 'bedroomcnt', 'regionidzip', 'censustractandblock', 'calculatedbathnbr', 'calculatedfinishedsquarefeet', 'taxamount', 'landtaxvaluedollarcnt', 'assessmentyear', 'taxvaluedollarcnt', 'structuretaxvaluedollarcnt', 'finishedsquarefeet12', 'yearbuilt', 'fips', 'fullbathcnt', 'latitude', 'roomcnt', 'rawcensustractandblock', 'logerror', 'propertycountylandusecode', 'parcelid']

df_reordered = df.reindex(columns=desired_column_order)

df_reordered.head()

In [ ]:
# Sort each column in the DataFrame, moving NaN values to the bottom
df_reordered = df_reordered.apply(lambda col: col.sort_values(na_position='last').values)
df_reordered.head()

In [ ]:
print("\nValue Counts for Categorical Columns:")
print('\n')
for column in df_reordered: #.select_dtypes(include='object'):
    print(f"Column: {column}")
    print(df_reordered[column].value_counts())
    print('\n')

In [ ]:
# Print value counts and missing value information for each column
print("\nValue Counts for Categorical Columns:")
print('\n')

for column in df_reordered:
    print(f"Column: {column}")
    value_counts = df_reordered[column].value_counts()
    total_missing = df_reordered[column].isnull().sum()
    percent_missing = (total_missing / len(df_reordered)) * 100
    print(value_counts)
    print(f"Total Missing Values: {total_missing}")
    print(f"Percent Missing: {percent_missing:.2f}%")
    print('\n')

In [ ]:
print("Shape of the DataFrame:", df_reordered.shape)
print('\n')
print("\nInfo:")
df_reordered.info()

In [ ]:
columns_with_nulls = df.columns[df.isnull().any()].tolist()

In [ ]:
columns_with_nulls

['calculatedfinishedsquarefeet',
 'finishedsquarefeet12',
 'fullbathcnt',
 'lotsizesquarefeet',
 'yearbuilt',
 'structuretaxvaluedollarcnt',
 'taxvaluedollarcnt',
 'landtaxvaluedollarcnt',
 'taxamount',
 'censustractandblock',
 'regionidzip',
 'regionidcity']

In [ ]:
# Assuming df is your original DataFrame
columns_with_null = [
    'regionidcity',
    'calculatedfinishedsquarefeet',
    'finishedsquarefeet12',
    'fullbathcnt',
    'lotsizesquarefeet',
    'yearbuilt',
    'structuretaxvaluedollarcnt',
    'taxvaluedollarcnt',
    'landtaxvaluedollarcnt',
    'taxamount',
    'censustractandblock',
    'regionidzip',
    'regionidcity'
]

# Create a dictionary of DataFrames where keys are column names and values are DataFrames with null values
null_dfs = {col: df[df[col].isnull()] for col in columns_with_null}

# You can now access each DataFrame using its respective column name as the key in the dictionary
# For example, to access the DataFrame for 'calculatedbathnbr':
# null_dfs['calculatedbathnbr']

In [ ]:


# Assuming sample_df is your DataFrame
columns_to_analyze = ['bathroomcnt', 'bedroomcnt', 'calculatedfinishedsquarefeet', 'taxvaluedollarcnt']

min_values = null_dfs['finishedsquarefeet12'][columns_to_analyze].min()
max_values = null_dfs['finishedsquarefeet12'][columns_to_analyze].max()
median_values = null_dfs['finishedsquarefeet12'][columns_to_analyze].median()

print(min_values)
print(max_values)
print(median_values)

bathroomcnt                         1.0
bedroomcnt                          1.0
calculatedfinishedsquarefeet      380.0
taxvaluedollarcnt               25218.0
dtype: float64
bathroomcnt                           5.5
bedroomcnt                            6.0
calculatedfinishedsquarefeet       5598.0
taxvaluedollarcnt               5043042.0
dtype: float64
bathroomcnt                          1.0
bedroomcnt                           2.0
calculatedfinishedsquarefeet       982.5
taxvaluedollarcnt               457902.0
dtype: float64

In [ ]:
filtered_df = df[df['calculatedbathnbr'].notnull()]

# Assuming filtered_df is the DataFrame where calculatedbathnbr is not null
# Check if calculatedbathnbr is equal to bathroomcnt
is_equal = filtered_df['calculatedbathnbr'] == filtered_df['bathroomcnt']

# To see the rows where they are equal:
equal_rows = filtered_df[is_equal]

# To see the rows where they are not equal:
not_equal_rows = filtered_df[~is_equal]

In [ ]:
not_equal_rows

Empty DataFrame
Columns: [parcelid, logerror, transactiondate, airconditioningdesc, heatingorsystemdesc, propertylandusedesc, bathroomcnt, bedroomcnt, calculatedbathnbr, calculatedfinishedsquarefeet, finishedsquarefeet12, fips, fireplacecnt, fullbathcnt, hashottuborspa, latitude, longitude, lotsizesquarefeet, poolcnt, propertycountylandusecode, propertyzoningdesc, rawcensustractandblock, roomcnt, threequarterbathnbr, yearbuilt, structuretaxvaluedollarcnt, taxvaluedollarcnt, assessmentyear, landtaxvaluedollarcnt, taxamount, taxdelinquencyflag, taxdelinquencyyear, censustractandblock, regionidzip, regionidcity, regionidcounty]
Index: []

In [ ]:
df.drop(columns=['calculatedbathnbr'], inplace= True)

In [ ]:
# Assuming filtered_df is the DataFrame where calculatedbathnbr is not null
filtered_by_region = df[df['regionidzip'] == 96186.0]
filtered_by_region

       parcelid  logerror transactiondate airconditioningdesc heatingorsystemdesc        propertylandusedesc  bathroomcnt  bedroomcnt  calculatedfinishedsquarefeet  finishedsquarefeet12    fips  fireplacecnt  fullbathcnt hashottuborspa    latitude    longitude  lotsizesquarefeet  poolcnt propertycountylandusecode propertyzoningdesc  rawcensustractandblock  roomcnt  threequarterbathnbr  yearbuilt  structuretaxvaluedollarcnt  taxvaluedollarcnt  assessmentyear  landtaxvaluedollarcnt  taxamount taxdelinquencyflag  taxdelinquencyyear  censustractandblock  regionidzip  regionidcity  regionidcounty
84     13854120  0.618889      2017-01-03                None                None  Single Family Residential          1.0         2.0                         480.0                 480.0  6059.0           0.0          1.0              N  33919726.0 -117955103.0             3000.0      0.0                       122               None            6.059001e+07      4.0                  0.0     1926.0                      4720.0            13817.0          2016.0                 9097.0     419.86                  Y                14.0         6.059001e+13      96186.0       18874.0          1286.0
85     13850030 -0.057162      2017-01-03                None                None  Single Family Residential          2.0         3.0                        1441.0                1441.0  6059.0           0.0          2.0              N  33943428.0 -117967412.0             7215.0      0.0                       122               None            6.059001e+07      7.0                  0.0     1955.0                     77926.0           315672.0          2016.0               237746.0    3619.30                  N                 0.0         6.059001e+13      96186.0           NaN          1286.0
349    13855414  0.039704      2017-01-04                None                None  Single Family Residential          2.0         4.0                        1477.0                1477.0  6059.0           0.0          2.0              N  33915361.0 -117972587.0             6300.0      0.0                       122               None            6.059002e+07      7.0                  0.0     1963.0                     41987.0            69536.0          2016.0                27549.0    1008.92                  N                 0.0         6.059002e+13      96186.0       18874.0          1286.0
481    13856175 -0.078229      2017-01-05                None                None  Single Family Residential          3.0         4.0                        2910.0                2910.0  6059.0           0.0          3.0              N  33906575.0 -117963972.0            11858.0      0.0                       122               None            6.059002e+07      0.0                  0.0     1999.0                    478187.0           916347.0          2016.0               438160.0   10236.96                  N                 0.0         6.059002e+13      96186.0       18874.0          1286.0
484    13855328 -0.005605      2017-01-05                None                None  Single Family Residential          2.0         4.0                        1681.0                1681.0  6059.0           0.0          2.0              N  33909781.0 -117949430.0            10716.0      0.0                       122               None            6.059002e+07      7.0                  0.0     1964.0                    101572.0           545202.0          2016.0               443630.0    6199.90                  N                 0.0         6.059002e+13      96186.0       18874.0          1286.0
...         ...       ...             ...                 ...                 ...                        ...          ...         ...                           ...                   ...     ...           ...          ...            ...         ...          ...                ...      ...                       ...                ...                     ...      ...                  ...        ...                         ...                ...             ...                    ...        ...                ...                 ...                  ...          ...           ...             ...
51972  13855583 -0.019351      2017-07-26                 Yes                None  Single Family Residential          3.0         4.0                        2320.0                2320.0  6059.0           0.0          3.0              N  33911082.0 -117950675.0            10632.0      1.0                       122               None            6.059002e+07      8.0                  0.0     1967.0                    158157.0           681505.0          2016.0               523348.0    7682.50                  N                 0.0         6.059002e+13      96186.0       18874.0          1286.0
51982  14153612  0.010180      2017-07-27                None                None  Single Family Residential          1.5         4.0                        1320.0                1320.0  6059.0           0.0          1.0              N  33934225.0 -117929756.0             6832.0      0.0                       122               None            6.059001e+07      7.0                  1.0     1955.0                     64581.0           477167.0          2016.0               412586.0    5536.00                  N                 0.0         6.059001e+13      96186.0       18874.0          1286.0
52024  12831304  0.075818      2017-08-01                None             Central  Single Family Residential          4.0         5.0                        3728.0                3728.0  6037.0           0.0          4.0              N  33947159.0 -117945385.0            39473.0      1.0                      0101             LHRA1*            6.037500e+07      0.0                  0.0     1957.0                    261661.0           779428.0          2016.0               517767.0    9056.30                  N                 0.0         6.037500e+13      96186.0       18875.0          3101.0
52138  14146308 -0.005005      2017-08-22             Central          Forced air  Single Family Residential          1.5         2.0                        1082.0                1082.0  6059.0           0.0          1.0              N  33913908.0 -117936617.0             1700.0      1.0                       122               None            6.059002e+07      5.0                  1.0     1976.0                     95941.0           217710.0          2016.0               121769.0    2637.66                  N                 0.0         6.059002e+13      96186.0       18874.0          1286.0
52153  14152335  0.031853      2017-08-23                None                None  Single Family Residential          3.0         5.0                        2874.0                2874.0  6059.0           2.0          3.0              N  33943735.0 -117928888.0             8586.0      1.0                       122               None            6.059001e+07      9.0                  0.0     1965.0                    171466.0           430395.0          2016.0               258929.0    5027.24                  N                 0.0         6.059001e+13      96186.0       18874.0          1286.0

[321 rows x 35 columns]

In [ ]:

# Assuming df is your original DataFrame

# Step 1: Filter out rows with null values in the "regionidcity" column to create df_check
df_check = df[df['regionidcity'].notnull()]

# Step 2: Extract unique "regionidzip" values
regionidzip_unique = df_check['regionidzip'].unique()

# Step 3: Count unique "regionidcity" values for each unique "regionidzip" value
city_counts = {}
for zip_code in regionidzip_unique:
    unique_cities = df_check[df_check['regionidzip'] == zip_code]['regionidcity'].nunique()
    city_counts[zip_code] = unique_cities

# Now, city_counts is a dictionary where the keys are unique regionidzip values
# and the values are the count of unique regionidcity values for each regionidzip.

In [ ]:
city_counts

{96978.0: 2,
 97099.0: 3,
 97078.0: 2,
 96330.0: 4,
 96293.0: 1,
 96325.0: 3,
 96173.0: 2,
 96374.0: 1,
 97051.0: 2,
 97107.0: 1,
 96962.0: 2,
 96003.0: 1,
 96971.0: 2,
 96954.0: 1,
 96018.0: 1,
 96237.0: 1,
 96957.0: 2,
 96352.0: 1,
 96008.0: 1,
 97005.0: 4,
 96122.0: 4,
 97067.0: 2,
 96116.0: 2,
 96271.0: 2,
 96349.0: 1,
 96450.0: 1,
 96447.0: 2,
 96000.0: 1,
 96291.0: 1,
 96133.0: 1,
 96486.0: 2,
 96361.0: 1,
 96983.0: 1,
 96998.0: 3,
 96414.0: 1,
 96464.0: 2,
 96517.0: 3,
 96982.0: 1,
 96241.0: 2,
 96488.0: 5,
 96522.0: 4,
 96961.0: 1,
 96370.0: 1,
 96987.0: 2,
 96366.0: 2,
 96387.0: 2,
 96507.0: 3,
 96506.0: 1,
 96494.0: 3,
 96212.0: 1,
 96337.0: 3,
 96049.0: 1,
 97018.0: 2,
 96229.0: 2,
 97079.0: 2,
 96437.0: 2,
 95983.0: 2,
 96185.0: 4,
 96025.0: 3,
 96058.0: 1,
 97063.0: 2,
 96452.0: 1,
 97068.0: 4,
 95984.0: 1,
 96280.0: 3,
 97003.0: 1,
 96389.0: 1,
 96208.0: 2,
 97024.0: 1,
 97318.0: 2,
 96101.0: 1,
 97041.0: 2,
 96186.0: 4,
 96398.0: 1,
 97089.0: 1,
 96384.0: 1,
 96192.0: 1,
 97091.0: 2,
 96989.0: 2,
 96136.0: 1,
 96369.0: 1,
 96206.0: 3,
 97106.0: 2,
 96378.0: 1,
 96342.0: 2,
 96995.0: 1,
 96426.0: 1,
 96020.0: 2,
 96401.0: 1,
 96969.0: 2,
 96137.0: 2,
 96024.0: 2,
 96531.0: 2,
 96197.0: 1,
 96981.0: 2,
 96967.0: 1,
 96980.0: 1,
 96943.0: 1,
 97328.0: 1,
 97020.0: 1,
 97048.0: 1,
 96183.0: 2,
 96451.0: 1,
 97021.0: 2,
 97023.0: 2,
 97025.0: 1,
 96083.0: 3,
 96958.0: 1,
 97081.0: 1,
 96265.0: 2,
 96514.0: 2,
 97330.0: 1,
 96966.0: 1,
 97323.0: 2,
 96092.0: 2,
 96990.0: 2,
 97084.0: 2,
 97035.0: 3,
 97039.0: 2,
 97083.0: 1,
 96268.0: 2,
 96354.0: 1,
 96410.0: 1,
 96180.0: 4,
 95993.0: 1,
 96267.0: 2,
 97329.0: 1,
 96004.0: 2,
 96102.0: 1,
 96974.0: 3,
 97004.0: 2,
 96986.0: 1,
 96385.0: 2,
 96181.0: 2,
 97317.0: 1,
 96373.0: 1,
 96013.0: 2,
 96023.0: 3,
 97098.0: 2,
 96479.0: 3,
 96193.0: 3,
 96383.0: 1,
 96368.0: 2,
 96150.0: 2,
 96201.0: 2,
 96149.0: 2,
 96327.0: 1,
 96174.0: 2,
 96489.0: 2,
 96213.0: 3,
 96001.0: 1,
 96284.0: 2,
 96242.0: 4,
 97097.0: 2,
 96240.0: 2,
 97116.0: 2,
 96364.0: 1,
 96446.0: 2,
 97118.0: 1,
 96375.0: 1,
 96027.0: 2,
 96228.0: 1,
 96993.0: 3,
 95999.0: 1,
 96513.0: 2,
 96523.0: 2,
 97047.0: 2,
 97109.0: 2,
 96379.0: 1,
 96103.0: 1,
 96117.0: 3,
 96415.0: 1,
 96163.0: 2,
 96965.0: 3,
 96134.0: 1,
 96161.0: 1,
 96123.0: 2,
 96215.0: 1,
 97344.0: 1,
 96490.0: 4,
 96222.0: 1,
 97008.0: 2,
 96129.0: 1,
 96524.0: 2,
 97026.0: 1,
 96107.0: 3,
 95987.0: 1,
 96341.0: 1,
 96485.0: 2,
 96221.0: 1,
 96496.0: 1,
 97043.0: 3,
 96230.0: 2,
 96296.0: 3,
 96492.0: 1,
 96393.0: 1,
 96169.0: 2,
 96505.0: 2,
 96127.0: 1,
 96171.0: 2,
 97319.0: 2,
 96351.0: 1,
 96047.0: 2,
 96113.0: 1,
 96497.0: 3,
 96091.0: 2,
 96247.0: 1,
 96100.0: 2,
 96030.0: 1,
 96424.0: 1,
 96959.0: 2,
 96533.0: 1,
 95985.0: 1,
 96339.0: 1,
 96046.0: 1,
 96320.0: 2,
 96940.0: 1,
 96515.0: 2,
 96449.0: 1,
 96321.0: 1,
 97016.0: 2,
 96292.0: 2,
 96022.0: 1,
 96346.0: 1,
 96028.0: 3,
 97066.0: 1,
 96019.0: 1,
 96356.0: 1,
 96475.0: 3,
 96278.0: 2,
 96508.0: 1,
 96979.0: 1,
 96124.0: 3,
 97040.0: 1,
 96239.0: 3,
 96473.0: 3,
 96985.0: 2,
 96012.0: 1,
 97104.0: 1,
 96106.0: 2,
 96324.0: 2,
 96371.0: 1,
 97006.0: 2,
 96026.0: 1,
 96996.0: 2,
 96270.0: 2,
 96111.0: 3,
 96469.0: 2,
 96121.0: 6,
 96016.0: 1,
 96045.0: 1,
 96126.0: 2,
 96436.0: 2,
 96005.0: 1,
 96217.0: 3,
 96433.0: 2,
 96244.0: 1,
 96245.0: 1,
 95997.0: 1,
 95989.0: 2,
 96095.0: 2,
 96109.0: 2,
 96326.0: 1,
 96172.0: 5,
 96125.0: 3,
 96975.0: 1,
 97050.0: 2,
 97007.0: 1,
 96295.0: 4,
 96946.0: 1,
 96220.0: 3,
 97065.0: 3,
 95982.0: 2,
 96152.0: 2,
 97101.0: 1,
 96210.0: 2,
 96017.0: 1,
 96104.0: 2,
 96510.0: 4,
 96282.0: 1,
 97052.0: 1,
 96090.0: 3,
 96948.0: 1,
 96218.0: 3,
 96225.0: 2,
 96120.0: 1,
 96474.0: 2,
 96465.0: 3,
 96119.0: 1,
 96044.0: 2,
 96216.0: 2,
 96015.0: 2,
 96037.0: 3,
 96951.0: 1,
 96086.0: 3,
 97027.0: 1,
 97059.0: 2,
 96162.0: 1,
 96939.0: 1,
 96525.0: 2,
 96190.0: 4,
 96021.0: 1,
 96110.0: 2,
 96014.0: 1,
 96105.0: 3,
 96007.0: 1,
 96412.0: 1,
 96246.0: 1,
 96480.0: 2,
 97094.0: 1,
 97001.0: 1,
 95986.0: 1,
 96204.0: 2,
 96273.0: 2,
 96043.0: 1,
 96050.0: 2,
 96160.0: 2,
 96438.0: 1,
 96964.0: 2,
 96159.0: 3,
 96207.0: 1,
 96973.0: 1,
 96377.0: 1,
 96275.0: 3,
 96006.0: 1,
 96338.0: 1,
 96355.0: 1,
 96411.0: 1,
 97037.0: 1,
 97064.0: 1,
 96135.0: 2,
 96294.0: 1,
 96322.0: 1,
 97113.0: 1,
 96203.0: 3,
 96478.0: 1,
 96420.0: 1,
 96029.0: 2,
 96042.0: 2,
 96226.0: 1,
 97298.0: 2,
 96097.0: 2,
 95992.0: 1,
 96170.0: 1,
 96128.0: 2,
 96336.0: 2,
 97119.0: 1,
 96238.0: 1,
 96952.0: 1,
 96040.0: 3,
 97324.0: 4,
 96941.0: 1,
 96087.0: 2,
 96403.0: 2,
 96234.0: 1,
 96947.0: 1,
 96088.0: 2,
 96009.0: 1,
 96010.0: 1,
 95988.0: 1,
 97108.0: 2,
 95995.0: 1,
 97316.0: 1,
 96151.0: 2,
 96434.0: 1,
 97331.0: 2,
 96289.0: 1,
 96236.0: 1,
 96956.0: 1,
 96039.0: 1,
 399675.0: 2,
 95994.0: 1,
 95996.0: 1,
 nan: 0,
 96323.0: 1,
 96467.0: 1,
 97092.0: 1,
 96038.0: 1,
 96148.0: 1}

In [ ]:
# Assuming df is your original DataFrame
unique_cities_for_zip = df[df['regionidzip'] == 96186]['regionidcity'].unique()
unique_cities_for_zip

array([18874.,    nan, 18875., 24812., 17150.])